/**
 * The SQL a production database needs, generated (SPEC.md §14).
 *
 *   pnpm launch:sql
 *
 * `pnpm seed` truncates every table and builds a world of 66 fake people, so it
 * must never be pointed at production. But production still needs the things
 * the seed happens to also create: the credit packs, the boards and classes,
 * the subject list, and the chapters for the launch board.
 *
 * Rather than a hand-maintained SQL file that drifts from the code the moment
 * somebody adds a subject, these are written out from the same definitions the
 * seed uses. `LAUNCH.md` tells you to run this and then `psql -f` the output,
 * and everything it emits is idempotent — running it twice changes nothing, so
 * it is safe to re-run after adding a board.
 */

import './bootstrap';

import { randomUUID } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { BOARD_SEEDS, boardCountrySeedRows } from '@/lib/curriculum/boards';
import { TOPIC_SEEDS } from '@/lib/curriculum/topics';
import { CREDIT_PACKS } from '@/lib/money/packs';
import { SUBJECTS } from '@/lib/tutors/subjects';

const OUT = join(process.cwd(), 'docs', 'launch');

/** Postgres string literal. Everything here is generated, but escape anyway. */
function q(value: string | null): string {
  if (value === null) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function header(title: string): string {
  return [
    `-- ${title}`,
    '--',
    '-- Generated by `pnpm launch:sql` from the definitions in src/lib.',
    '-- Do not edit by hand: regenerate it, or the code and the database drift.',
    '-- Every statement is idempotent — running this twice changes nothing.',
    '',
  ].join('\n');
}

function packsSql(): string {
  const rows = CREDIT_PACKS.map(
    (pack) =>
      `  (${q(pack.id)}, ${q(pack.name)}, ${pack.paidCents}, ${pack.creditsCents}, ${pack.sortOrder}, true, ${
        pack.firstPurchaseOnly ?? false
      })`,
  ).join(',\n');

  return [
    header('Credit packs and the platform accounts'),
    'insert into credit_packs (id, name, paid_cents, credits_cents, sort_order, active, first_purchase_only)',
    'values',
    rows,
    'on conflict (id) do update set',
    '  name = excluded.name,',
    '  paid_cents = excluded.paid_cents,',
    '  credits_cents = excluded.credits_cents,',
    '  sort_order = excluded.sort_order,',
    '  first_purchase_only = excluded.first_purchase_only;',
    '',
    '-- The platform side of the ledger. `appendLedger` upserts this row on the',
    '-- first entry, but creating it here means the admin dashboard and the',
    '-- reconciliation job read a zero rather than a null on day one.',
    "insert into platform_accounts (account, balance_cents) values ('platform_revenue', 0)",
    '  on conflict (account) do nothing;',
    '',
  ].join('\n');
}

function curriculumSql(): string {
  const boardRows = BOARD_SEEDS.map(
    (board) => `  (${q(board.id)}, ${q(board.name)}, ${board.sortOrder})`,
  ).join(',\n');

  const levelRows = BOARD_SEEDS.flatMap((board) =>
    board.levels.map(
      (level) =>
        `  (${q(level.id)}, ${q(board.id)}, ${q(level.name)}, ${q(level.stage)}, ${level.sortOrder})`,
    ),
  ).join(',\n');

  const countryRows = boardCountrySeedRows()
    .map((row) => `  (${q(row.boardId)}, ${q(row.country)}, ${row.sortOrder})`)
    .join(',\n');

  // Subjects have generated ids, so they are inserted by slug and only when the
  // slug is new — a production database that already has them keeps its own.
  const subjectRows = SUBJECTS.map(
    (subject, index) => `  (${q(randomUUID())}, ${q(subject.slug)}, ${q(subject.name)}, ${index})`,
  ).join(',\n');

  const topicRows = TOPIC_SEEDS.flatMap((set) =>
    set.topics.map(
      (topic, index) =>
        `  (${q(set.boardId)}, ${q(set.levelId)}, ${q(set.subjectSlug)}, ${q(topic.name)}, ${q(
          topic.reference ?? null,
        )}, ${index})`,
    ),
  ).join(',\n');

  return [
    header('Boards, classes, subjects and chapters'),
    'insert into boards (id, name, sort_order)',
    'values',
    boardRows,
    'on conflict (id) do update set name = excluded.name, sort_order = excluded.sort_order;',
    '',
    'insert into curriculum_levels (id, board_id, name, stage, sort_order)',
    'values',
    levelRows,
    'on conflict (board_id, id) do update set name = excluded.name, stage = excluded.stage, sort_order = excluded.sort_order;',
    '',
    'insert into board_countries (board_id, country, sort_order)',
    'values',
    countryRows,
    'on conflict do nothing;',
    '',
    'insert into subjects (id, slug, name, sort_order)',
    'values',
    subjectRows,
    'on conflict (slug) do nothing;',
    '',
    '-- Chapters, resolved against the subject rows above by slug so this file',
    '-- does not need to know the generated subject ids.',
    'insert into topics (board_id, level_id, subject_id, name, reference, sort_order)',
    'select v.board_id, v.level_id, s.id, v.name, v.reference, v.sort_order',
    'from (values',
    topicRows,
    ') as v(board_id, level_id, subject_slug, name, reference, sort_order)',
    'join subjects s on s.slug = v.subject_slug',
    'on conflict (board_id, level_id, subject_id, name) do nothing;',
    '',
  ].join('\n');
}

function main(): void {
  mkdirSync(OUT, { recursive: true });

  const packs = packsSql();
  const curriculum = curriculumSql();

  writeFileSync(join(OUT, 'packs.sql'), packs);
  writeFileSync(join(OUT, 'curriculum.sql'), curriculum);

  const chapters = TOPIC_SEEDS.reduce((total, set) => total + set.topics.length, 0);
  const levels = BOARD_SEEDS.reduce((total, board) => total + board.levels.length, 0);

  console.log('Wrote docs/launch/packs.sql');
  console.log(`  ${CREDIT_PACKS.length} credit packs, 1 platform account`);
  console.log('Wrote docs/launch/curriculum.sql');
  console.log(
    `  ${BOARD_SEEDS.length} boards · ${levels} classes · ${SUBJECTS.length} subjects · ${chapters} chapters`,
  );
  console.log('');
  console.log('Apply with:');
  console.log('  psql "$DATABASE_URL" -f docs/launch/packs.sql');
  console.log('  psql "$DATABASE_URL" -f docs/launch/curriculum.sql');
}

main();
