import Link from 'next/link';
import { pageMetadata } from '@/lib/seo/site';
import { PublicShell, actionLink, textLink } from '../_components/public-shell';

export const metadata = pageMetadata('Teach on Tutorly — 22% commission, 16% on rebookings', 'Set your rates, choose whether to offer free trials, and request payouts from US$100. Meet students looking for the curriculum you teach.', '/teach');

export default function TeachPage() {
  return <PublicShell>
    <section className="grid gap-9 lg:grid-cols-[1.3fr_1fr]">
      <div><p className="text-sm font-semibold uppercase tracking-widest text-primary">For independent tutors</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Your students come back.<br /><span className="text-primary">You keep more.</span></h1><p className="mt-6 max-w-xl text-lg leading-8">Teach the courses you know, set your own lesson rates and build a continuing relationship with your students. Our standard commission drops from 22% to 16% when an eligible student rebooks.</p><Link href="/tutor/onboarding" className={`${actionLink} mt-7`}>Create your tutor profile</Link><p className="mt-4 text-sm leading-6">Your profile is reviewed before it appears in search. An introduction video and supporting credentials are required.</p></div>
      <div className="self-center rounded-2xl border bg-card p-8"><p className="text-sm font-semibold">On a US$25 lesson</p><dl className="mt-6 space-y-6"><div><dt className="text-sm">You receive from a new student</dt><dd className="mt-2 text-4xl font-semibold tracking-tight">$19.50</dd></div><div className="border-t pt-6"><dt className="text-sm">You receive on an eligible rebooking</dt><dd className="mt-2 text-4xl font-semibold tracking-tight text-primary">$21.00</dd></div></dl><p className="mt-5 text-xs leading-6">Illustration at the standard rates, before your taxes and any disclosed payout fee. A lower negotiated commission can apply.</p></div>
    </section>
    <section className="mt-16" aria-labelledby="comparison-heading"><h2 id="comparison-heading" className="text-2xl font-semibold">Know the commission before you join</h2><div className="mt-6 overflow-x-auto rounded-xl border"><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">Tutorly and Preply commission comparison</caption><thead className="bg-secondary"><tr><th scope="col" className="p-4">Commission and trials</th><th scope="col" className="p-4">Tutorly</th><th scope="col" className="p-4">Preply</th></tr></thead><tbody className="divide-y"><tr><th scope="row" className="p-4 font-medium">Standard paid-lesson commission</th><td className="p-4">22%, falling to 16% on eligible rebookings</td><td className="p-4">33%, falling to 18% with total teaching hours</td></tr><tr><th scope="row" className="p-4 font-medium">Trial lessons</th><td className="p-4">Free to the student; optional and tutor-approved; no earnings or commission</td><td className="p-4">100% commission on every trial with a new student</td></tr><tr><th scope="row" className="p-4 font-medium">Tutor earnings on a $25 paid lesson</th><td className="p-4">$19.50, or $21.00 at 16%</td><td className="p-4">$16.75 at 33%, or $20.50 at 18%</td></tr></tbody></table></div><p className="mt-4 max-w-3xl text-sm leading-7">Comparison checked 5 September 2026 against <a className={textLink} href="https://help.preply.com/en/articles/4171383-preply-commission-model">Preply’s commission model</a>. These are different discount rules: Tutorly rewards repeat students; Preply uses cumulative teaching hours. Dollar examples hold the listed lesson price constant and compare commission only, not lesson duration, taxes, fees or likely demand.</p></section>
    <section className="mt-14 grid gap-6 md:grid-cols-3" aria-label="Teaching on your terms">
      {[
        ['Set your own rates', 'Choose your permitted hourly rate and half-hour option. Confirmed bookings keep the price and commission they were booked at.'],
        ['Choose your trials', 'Offer 10, 15 or 20 minutes only if it suits your teaching. Set a weekly cap and accept or decline each request. Free trials are not compulsory.'],
        ['Request payouts from $100', 'Once at least US$100 is available, request an eligible payout. Requests are reviewed manually and tracked through approval, processing and payment.'],
      ].map(([title, copy]) => <div key={title} className="rounded-xl border bg-card p-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7">{copy}</p></div>)}
    </section>
    <section className="mt-14 max-w-3xl"><h2 className="text-2xl font-semibold">When does 16% apply?</h2><p className="mt-4 leading-8">The student must already have completed a paid session with you when the next booking is created. Several lessons booked before that first session happens do not automatically receive the returning-student rate. A lower individually agreed commission is honoured, and old bookings keep their original rate.</p><h2 className="mt-9 text-2xl font-semibold">Teach safely. Build trust.</h2><p className="mt-4 leading-8">Most students are minors. Keep lessons and messages on the platform, respect guardian arrangements and maintain clear professional boundaries. Credential verification supports trust but does not guarantee teaching quality, student numbers or income. You teach as an independent contractor and are responsible for applicable taxes and work permissions.</p><p className="mt-4 leading-7">Read the draft <Link className={textLink} href="/tutor-agreement">Tutor Agreement</Link> and <Link className={textLink} href="/child-safety">Child Safety Policy</Link> before applying.</p><Link href="/tutor/onboarding" className={`${actionLink} mt-7`}>Start your application</Link></section>
  </PublicShell>;
}
