import Link from 'next/link';
import { listCreditPacks } from '@/db/purchases';
import { formatUsd, pageMetadata } from '@/lib/seo/site';
import { PublicShell, actionLink, textLink } from '../_components/public-shell';

export const metadata = pageMetadata('How credits and lesson pricing work', 'Understand Tutorly credit packs, tutor-set lesson rates, credit refunds, optional trials and the US$100 tutor payout threshold.', '/pricing');
// Packs are administrator-editable; stale hard-coded bonuses would mislead buyers.
export const dynamic = 'force-dynamic';

export default async function PricingPage() {
  const packs = await listCreditPacks();
  return <PublicShell>
    <header className="max-w-3xl"><p className="font-semibold text-primary">Pay for the lessons you choose</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">A lesson price.<br />A credit balance.<br /><span className="text-primary">No guesswork.</span></h1><p className="mt-6 text-lg leading-8">One credit is US$1 of lesson value. Tutors set their own prices for 30- and 60-minute sessions. Browse, choose a tutor and see the price before you buy the credits you need.</p><Link className={`${actionLink} mt-7`} href="/">Find a lesson first</Link></header>
    <section className="mt-12 rounded-xl border-2 border-primary p-6" aria-labelledby="credit-rule"><h2 id="credit-rule" className="text-xl font-semibold">Credits stay available for learning</h2><p className="mt-3 max-w-3xl leading-8">Credits never expire. They are non-refundable to cash under the standard policy: approved lesson refunds return as credits to your wallet. Credits are not withdrawable money. Mandatory legal refund rights still apply.</p></section>
    <section className="mt-12" aria-labelledby="pack-heading"><h2 id="pack-heading" className="text-2xl font-semibold">Current credit packs</h2><p className="mt-3 leading-7">These packs come from the current catalogue. Check the final offer, eligibility and any disclosed payment or conversion charge before purchase.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{packs.map((pack) => <article key={pack.id} className="rounded-xl border bg-card p-6"><h3 className="text-lg font-semibold">{pack.name}</h3><p className="mt-4 text-3xl font-semibold">{formatUsd(pack.paidCents)}</p><p className="mt-2">Adds {formatUsd(pack.creditsCents)} of lesson credits</p>{pack.creditsCents > pack.paidCents && <p className="mt-2 font-medium text-primary">Includes {formatUsd(pack.creditsCents - pack.paidCents)} bonus lesson value</p>}{pack.firstPurchaseOnly && <p className="mt-3 text-sm leading-6">Only for your first credit purchase, once per person. It does not guarantee a complete lesson at every tutor’s rate.</p>}</article>)}</div><Link href="/credits" className={`${textLink} mt-5 inline-block`}>View eligible packs in your account</Link></section>
    <section className="mt-12 max-w-3xl"><h2 className="text-2xl font-semibold">Follow one booking</h2><ol className="mt-5 list-decimal space-y-4 pl-6 leading-8"><li>Choose a tutor’s 30- or 60-minute slot and check its price in credits.</li><li>Sign in to confirm. If you need more credits, the booking flow offers a top-up while your temporary slot hold remains valid.</li><li>Confirm the booking. Its price is reserved from your wallet and remains fixed even if the tutor changes their rates later.</li><li>Meet in the platform classroom. The normal 24-hour dispute window follows the lesson before funds settle to the tutor.</li></ol></section>
    <section className="mt-12" aria-labelledby="cancellation-heading"><h2 id="cancellation-heading" className="text-2xl font-semibold">If your plans change</h2><dl className="mt-5 grid gap-4 md:grid-cols-3">{[['More than 24 hours before', '100% returned as credits'], ['2–24 hours before', '50% returned as credits'], ['Less than 2 hours before', 'No standard credit refund']].map(([time, outcome]) => <div key={time} className="rounded-xl border p-5"><dt className="font-semibold">{time}</dt><dd className="mt-2">{outcome}</dd></div>)}</dl><p className="mt-5 max-w-3xl leading-8">Exactly 24 hours and exactly 2 hours fall in the half-refund tier. A tutor cancellation or tutor no-show returns the full lesson price as credits. If you do not attend and the tutor joins and waits 10 minutes, the lesson is charged in full. Read the <Link className={textLink} href="/refund-policy">draft Refund Policy</Link> for technical failures and disputes.</p></section>
    <section className="mt-12 grid gap-8 md:grid-cols-2"><div><h2 className="text-2xl font-semibold">Want to meet before booking?</h2><p className="mt-4 leading-8">Some tutors offer a free trial of 10, 15 or 20 minutes. Trials are optional and require the tutor’s approval. They move no credits, and a request is not a confirmed appointment.</p></div><div><h2 className="text-2xl font-semibold">Teaching here?</h2><p className="mt-4 leading-8">The standard commission is 22%, falling to 16% for eligible rebookings. Payouts start at US$100 in available earnings and require manual review. Student credits and tutor earnings are separate balances.</p><Link className={`${textLink} mt-4 inline-block`} href="/teach">See what tutors receive</Link></div></section>
    <p className="mt-12 border-t pt-6 leading-7">For under-18 students, a parent or guardian should review the booking and approve spending. Read our <Link className={textLink} href="/child-safety">Child Safety Policy</Link>.</p>
  </PublicShell>;
}
