-- Credit packs and the platform accounts
--
-- Generated by `pnpm launch:sql` from the definitions in src/lib.
-- Do not edit by hand: regenerate it, or the code and the database drift.
-- Every statement is idempotent — running this twice changes nothing.

insert into credit_packs (id, name, paid_cents, credits_cents, sort_order, active, first_purchase_only)
values
  ('taste', 'First lesson', 500, 500, 0, true, true),
  ('starter', 'Starter', 1000, 1000, 1, true, false),
  ('standard', 'Standard', 2500, 2500, 2, true, false),
  ('plus', 'Plus', 5000, 5150, 3, true, false),
  ('pro', 'Pro', 10000, 10500, 4, true, false)
on conflict (id) do update set
  name = excluded.name,
  paid_cents = excluded.paid_cents,
  credits_cents = excluded.credits_cents,
  sort_order = excluded.sort_order,
  first_purchase_only = excluded.first_purchase_only;

-- The platform side of the ledger. `appendLedger` upserts this row on the
-- first entry, but creating it here means the admin dashboard and the
-- reconciliation job read a zero rather than a null on day one.
insert into platform_accounts (account, balance_cents) values ('platform_revenue', 0)
  on conflict (account) do nothing;
